title: Global Groundwater Seminar 2026
description: Multi-physics groundwater characterization - UTIG/Stony Brook
theme: jekyll-theme-cayman
show_downloads: true
google_analytics: # Add your UA code here if you want to track hits
